---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: example-com
  namespace: cert-manager
spec:
  secretName: example-com-tls 
  issuerRef:
    name: ca-issuer
    kind: Issuer
  commonName: example.com
  dnsName: 
   - www.example.com